import { Inter } from "next/font/google";
import "./globals.css";
import { HistoryContext } from "./context/historycontext";
import { ConversationContext } from "./context/convoContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Trip Pal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConversationContext>
          <HistoryContext>
            {children}
          </HistoryContext>
        </ConversationContext>
      </body>
    </html>
  );
}
