import { Inter } from "next/font/google";
import "./globals.css";
import { HandleApp } from "./appcontext";
import { HistoryContext } from "./(historycomp)/historycontext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Trip Pal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HandleApp>
          <HistoryContext>
            {children}
          </HistoryContext>
        </HandleApp>
      </body>
    </html>
  );
}
